services:
  competencia:
    container_name: competencia_web
    build: .
    ports:
      - 8000:8000
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.5"
          memory: "256M"
